=== ea9898/schr-root/application/schr-scheduler/esu-sae-listener-scheduler/sae-listener-domain/src/main/resources/json.schema/ErpChangePatientSchoolBase.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://emias.mos.ru/erpschool/ErpChangePatient/v1",
  "description": "Универсальная схема топиков сущностей пациента",
  "type": "object",
  "properties": {
    "id": {
      "type": "integer",
      "description": "ИД события в ЕРП"
    },
    "operationDate": {
      "type": "string",
      "format": "date-time",
      "description": "Дата и время создания сообщения"
    },
    "emiasId": {
      "type": "integer",
      "description": "Идентификатор пациента в ЕМИАС"
    },
    "uklErp": {
      "type": "string",
      "description": "Уникальный идентификатор застрахованного лица в ЕМИАС.ЕРП"
    },
    "studentId": {
      "type": "string",
      "format": "uuid",
      "description": "Идентификатор учащегося в ЕМИАС.Учащиеся (ранее - person_uuid в КИС ГУСОЭВ). Формат: GUID"
    },
    "studentPersonId": {
      "type": "string",
      "format": "uuid",
      "description": "Идентификатор персоны-учащегося в МЭШ. Формат: GUID"
    },
    "patientStudentLinkStatus": {
      "$ref": "#/definitions/RecStatus",
      "description": "Статус записи связи пациента и учащегося. Возможные значения: Y – Актуальная; N – Не актуальная"
    },
    "patientType": {
      "$ref": "#/definitions/PatientType",
      "description": "Тип пациента. Возможные значения: I - идентифицированный (пациент с действующим и/или недействующим полисом ОМС в Системе); P - неполные данные (пациент без полиса ОМС в Системе)"
    },
    "patientSystemCode": {
      "type": "string",
      "description": "Код системы источника данных. Указывается для пациента с типом P - неполные данные"
    },
    "patientRecStatus": {
      "$ref": "#/definitions/RecStatus",
      "description": "Статус записи пациента. Возможные значения: Y – Актуальная, N – Не актуальная"
    },
    "entityName": {
      "type": "string",
      "description": "Наименование сущности. Возможные значения: schoolAttachment"
    },
    "entityData": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/EntityData"
      },
      "description": "Сведения записи сущности"
    }
  },
  "required": [
    "id",
    "operationDate",
    "uklErp",
    "studentId",
    "patientStudentLinkStatus",
    "patientType",
    "patientRecStatus",
    "entityName"
  ],
  "definitions": {
    "RecStatus": {
      "type": "string",
      "enum": [
        "Y",
        "N"
      ]
    },
    "PatientType": {
      "type": "string",
      "enum": [
        "I",
        "P"
      ]
    },
    "Value": {
      "type": "object",
      "properties": {
        "id": {
          "type": "integer",
          "description": "Идентификатор значения. Может быть заполнен только для атрибута с типом dictionary"
        },
        "code": {
          "type": "string",
          "description": "Код значения. Может быть заполнен только для атрибута с типом dictionary"
        },
        "value": {
          "type": "string",
          "description": "Значение. Для типа dictionary заполняется наименованием значения из справочника. При этом, если в соответствующем справочнике будет несколько наименований, то будет указываться полное"
        }
      }
    },
    "Attribute": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "description": "Наименование атрибута записи"
        },
        "type": {
          "type": "string",
          "description": "Возможные значения (жестко не фиксированы): string; integer; date (формат данных 'YYYY-MM-DD'); dateTime (формат данных 'YYYY-MM-DD'T'HH24:MI:SS.SSSZ', миллисекунды не обязательные); double; boolean; dictionary; guid"
        },
        "value": {
          "$ref": "#/definitions/Value",
          "description": "Значение атрибута"
        }
      },
      "required": [
        "name",
        "type"
      ]
    },
    "EntityData": {
      "type": "object",
      "properties": {
        "attributes": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Attribute"
          },
          "description": "Сведения записи сущности"
        }
      },
      "required": [
        "attributes"
      ]
    }
  }
}

=== ea9898/schr-root/application/schr-scheduler/esu-sae-listener-scheduler/sae-listener-application/src/test/resources/json/SchoolAttachmentEventWrong92.json
{
   "id": 613,
   "operationDate": "2022-06-24T12:43:39.95+03:00",
   "emiasId": 1155761388036,
   "uklErp": "31583221",
   "studentId": "c5d6951e-0cad-49c0-e053-0676020abc2e",
   "studentPersonId": "2c7ac8f6-97a9-4b4e-9cb7-e7820559a8a2",
   "patientStudentLinkStatus": "Y",
   "patientType": "I",
   "patientRecStatus": "Y",
   "entityName": "schoolAttachment",
   "entityData": [
      {
         "attributes": [
            {
               "name": "attachId",
               "type": "integer",
               "value": {
                  "value": "test"
               }
            },
            {
               "name": "attachType",
               "type": "dictionary",
               "value": {
                  "id": 128619874,
                  "code": "9",
                  "value": "школьное"
               }
            },
            {
               "name": "attachForm",
               "type": "dictionary",
               "value": {
                  "id": 128620020,
                  "code": "60",
                  "value": "Прикрепление к классу"
               }
            },
            {
               "name": "organizationId",
               "type": "integer",
               "value": {
                  "value": "200001565467"
               }
            },
            {
               "name": "areaId",
               "type": "integer",
               "value": {
                  "value": "17411886030"
               }
            },
            {
               "name": "attachStartDate",
               "type": "date",
               "value": {
                  "value": "2021-06-24"
               }
            },
            {
               "name": "attachEndDate",
               "type": "date",
               "value": {}
            },
            {
               "name": "isActual",
               "type": "long",
               "value": {
                  "value": "true"
               }
            },
            {
               "name": "classUid",
               "type": "guid",
               "value": {
                  "value": "275fa2c3-ada3-4ad1-8d3d-0ac7dd0d99a7"
               }
            },
            {
               "name": "academicYear",
               "type": "dictionary",
               "value": {
                  "id": 22,
                  "value": "2021/2022"
               }
            },
            {
               "name": "educationForm",
               "type": "dictionary",
               "value": {
                  "id": 1,
                  "value": "Очная"
               }
            },
            {
               "name": "deductionReason",
               "type": "dictionary",
               "value": {}
            },
            {
               "name": "trainingBeginDate",
               "type": "date",
               "value": {
                  "value": "2021-06-24T00:00"
               }
            },
            {
               "name": "trainingEndDate",
               "type": "date",
               "value": {
                  "value": "2099-01-01T00:00"
               }
            }
         ]
      }
   ]
}

=== ea9898/schr-root/application/schr-scheduler/esu-sae-handler-scheduler/sae-handler-application/src/test/resources/json/schoolAttachmentEvent.json
{
  "id": 29,
  "operationDate": "2022-06-23T18:47:30.868+03:00",
  "emiasId": 18027361,
  "uklErp": "30416317",
  "studentId": "e5c9b68a-a3c7-6688-e043-a2997e0ac8c8",
  "studentPersonId": "7445b4ed-f762-49c1-a58d-2edd164c95e3",
  "patientStudentLinkStatus": "Y",
  "patientType": "I",
  "patientRecStatus": "Y",
  "entityName": "schoolAttachment",
  "entityData": [
    {
      "attributes": [
        {
          "name": "attachId",
          "type": "integer",
          "value": {
            "value": "124922913"
          }
        },
        {
          "name": "attachType",
          "type": "dictionary",
          "value": {
            "id": 128619874,
            "code": "9",
            "value": "школьное"
          }
        },
        {
          "name": "attachForm",
          "type": "dictionary",
          "value": {
            "id": 128620020,
            "code": "60",
            "value": "Прикрепление к классу"
          }
        },
        {
          "name": "organizationId",
          "type": "integer",
          "value": {
            "value": "200001512243"
          }
        },
        {
          "name": "areaId",
          "type": "integer",
          "value": {
            "value": "17411929190"
          }
        },
        {
          "name": "attachStartDate",
          "type": "date",
          "value": {
            "value": "2021-08-23"
          }
        },
        {
          "name": "attachEndDate",
          "type": "date",
          "value": {}
        },
        {
          "name": "isActual",
          "type": "long",
          "value": {
            "value": "true"
          }
        },
        {
          "name": "classUid",
          "type": "guid",
          "value": {
            "value": "43fdbd33-0766-40a2-a84c-d0b4492499ab"
          }
        },
        {
          "name": "academicYear",
          "type": "dictionary",
          "value": {
            "id": 22,
            "value": "2021/2022"
          }
        },
        {
          "name": "educationForm",
          "type": "dictionary",
          "value": {
            "id": 1,
            "value": "Очная"
          }
        },
        {
          "name": "deductionReason",
          "type": "dictionary",
          "value": {}
        },
        {
          "name": "trainingBeginDate",
          "type": "date",
          "value": {
            "value": "2021-08-23T00:00"
          }
        },
        {
          "name": "trainingEndDate",
          "type": "date",
          "value": {
            "value": "2099-01-01T00:00"
          }
        }
      ]
    }
  ]
}
